language: python
python:
  - "3.6.1"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pytest tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing # or py.test for Python versions 3.5 and below
after_success:
  - coveralls